name: Checks
on:
  - pull_request

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install deps
      run: yarn install --frozen-lockfile
    - name: Run build
      run: yarn build

  BuildCDK:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install deps
      run: yarn install --frozen-lockfile
    - name: Run build-cdk
      run: yarn build-cdk

  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install deps
      run: yarn install --frozen-lockfile
    - name: Run lint
      run: yarn lint

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install deps
      run: yarn install --frozen-lockfile
    - name: Setup DynamoDB Local
      uses: rrainn/dynamodb-action@v2.0.1
      with:
        port: 8000
        cors: '*'
    - name: Run Test
      run: yarn test